name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - id: auth
      name: Authorize Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - id: deploy
      name: Deploy to Google Cloud Functions
      uses: google-github-actions/deploy-cloud-functions@v1
      with:
        name: 'helloWorld'
        runtime: 'nodejs14'
        source_dir: './'
        region: 'us-east1'
        project_id: ${{ secrets.GCP_PROJECT }}
        baseURL: 'https://cloudfunctions.googleapis.com/v2'

    - name: Print the Cloud Function URL
      run: echo "${{ steps.deploy.outputs.url }}"
